[package]
name = "services"
version = "1.0.0"
authors = ["Nexus Labs"]
edition = "2018"
description = "Nexus services contracts"
license = "Apache-2.0"
repository = "https://github.com/Nexus-Protocol/services-contracts"
homepage = "todo"
documentation = "todo"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = true

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.8.1" }
cosmwasm-std = { version = "0.16.1", features = ["iterator"] }
schemars = "0.8.1"
serde = { version = "1.0.126", default-features = false, features = ["derive"] }
terraswap = "2.4.0"
